# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate and concatenate multiple integer sequences
#' 
#' This generates multiple integer sequences and concatenates them.
#'
#' @param from,to the starting and (maximal) end values of the sequences. 
#' Multiple can be given.
#'
#' @returns An integer vector of multiple concatenated integer sequences.
#' @export
#' @author Sercan Kahveci
#'
#' @examples
#' seq_composite(from=c(1,7),to=c(3,8))
#' 
seq_composite <- function(from, to) {
    .Call('_skMisc_seq_composite', PACKAGE = 'skMisc', from, to)
}

carryforward_numeric <- function(x) {
    .Call('_skMisc_carryforward_numeric', PACKAGE = 'skMisc', x)
}

EnumerateFrom <- function(sequences, times, target) {
    .Call('_skMisc_EnumerateFrom', PACKAGE = 'skMisc', sequences, times, target)
}

